name: 'build-delga'
description: 'Build DELGA distribution file using DEIGDE CI'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  projectFile:
    description: 'Path to the project-file to use (*.degp), within the repository.'
    required: true
    default: 'project.degp'
  profile:
    description: 'Name of profile to use.'
    required: true
    default: 'Release'
  outputDir:
    description: 'Directory to store run outputs.'
    required: false
    default: 'deigde-output'
runs:
  using: 'node20'
  main: 'action.js'
