name: 'build-delga'
description: 'Build DELGA distribution file using DEIGDE CI'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  projectFile:
    description: 'Path to the project-file to use (*.degp), within the repository.'
    required: true
    default: 'project.degp'
  profile:
    description: 'Name of profile to use.'
    required: true
    default: 'Release'
  outputDir:
    description: 'Directory to store run outputs.'
    required: false
    default: 'deigde-output'
runs:
  runs-on: ubuntu-latest
  steps:
    name: Run IGDE-CI
    run: |
      docker run --rm --workdir /github/workspace \
        -v "${{ github.workspace }}":"/github/workspace" \
        -v "${{ github.workspace }}/${{ inputs.outputDir }}":"/opt/deigde-output" \
          lordofdragons/deigde-ci:latest \
            "/github/workspace/${{ inputs.projectFile }}" \
            --project.profile.distribute \
            "${{ inputs.profile }}"
