name: 'build-delga'
description: 'Build DELGA distribution file using DEIGDE CI'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  projectFile:
    description: 'Path to the project-file to use (*.degp), within the repository.'
    required: true
    default: 'project.degp'
  profile:
    description: 'Name of profile to use.'
    required: true
    default: 'Release'
runs:
  container:
    image: docker://lordofdragons/deigde-ci:latest
    volumes:
      - ${{ github.workspace }}/logs:~/.config/deigde/logs
    args:
      - /github/workspace/${{ inputs.projectFile }}
      - --project.profile.distribute
      - ${{ inputs.profile }}
